### ISSUE TITLE
执行 bdh --help 命令时报错，日志如下

### ISSUE THREAD

**Issue by dxhuii** [bangumi-data/helper#1]
`/Users/plain/.nvm/versions/node/v5.0.0/lib/node_modules/bangumi-data-helper/bin/bdh.js:12
const { merge, readJSON, writeJSON, classify } = require('../lib/utils.js');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3`

**Comment by dxhuii** [comment]
已经解决了，应该是我的NODE版本太低，不支持const的问题
